VPC_ID: vpc-027ff20d81be70a51 # vpc_id
SUBNET1_ID: subnet-0a02aed08a726ab3b # the subnets of the vpc
SUBNET2_ID: subnet-0c6d6d4a9baa1417e # the subnets of the vpc
VPC_ENDPOINT_ID: "vpce-008b9e2acfbda7043"
DICT_KEY_USERNAME: "username"
DICT_KEY_PASSWORD: "password"
DICT_KEY_USERPRINCIPALNAME: "userPrincipalName"
DICT_KEY_BIND_DN: "ldap_default_bind_dn"
SECRETS_MANAGER_REGION: "eu-central-1"
EXCLUDE_CHARACTERS_USER: "$/`'\"\\"
EXCLUDE_CHARACTERS_PW: "/'\"\\"
EXCLUDE_CHARACTERS_NEW_PW: "@$/`'\"\\"
LDAP_SERVER_LIST: '["ldaps://vt1dceuc1001.vt1.vitesco.com", "ldaps://vt1dceuc1002.vt1.vitesco.com"]'
LDAP_SERVER_PORT: "636"
