VPC_ID: vpc-0d74ad4b95ae1c2e1 # vpc_id
SUBNET1_ID: subnet-0c7208481c2dc12c0 # the subnets of the vpc
SUBNET2_ID: subnet-06d34103fcb97f566 # the subnets of the vpc
DICT_KEY_USERNAME: "username"
DICT_KEY_PASSWORD: "password"
DICT_KEY_DN: ""
SECRETS_MANAGER_REGION: "eu-central-1"
EXCLUDE_CHARACTERS_USER: "$/`'\"\\"
EXCLUDE_CHARACTERS_PW: "/'\"\\"
EXCLUDE_CHARACTERS_NEW_PW: "@$/`'\"\\()"
LDAP_SERVER_LIST: '["ldaps://vt1dceuc1001.vt1.vitesco.com", "ldaps://vt1dceuc1002.vt1.vitesco.com"]'
LDAP_SERVER_PORT: "636"
LDAP_BASE_DN: "dc=vt1,dc=vitesco,dc=com"
