VPC_ID: vpc-0d43eda6a96215a22 # vpc_id
SUBNET1_ID: subnet-02ecfbaf8709fc021 # the subnets of the vpc
SUBNET2_ID: subnet-065e73e2c2ee20d2c # the subnets of the vpc
SECRETS_MANAGER_KEY_USERNAME: "username"
SECRETS_MANAGER_KEY_PASSWORD: "password"
SECRETS_MANAGER_KEY_DN: ""
SECRETS_MANAGER_REGION: "eu-central-1"
EXCLUDE_CHARACTERS_USER: "$/`'\"\\"
EXCLUDE_CHARACTERS_PW: "/'\"\\"
EXCLUDE_CHARACTERS_NEW_PW: "@$/`'\"\\()"
LDAP_SERVER_LIST: '["ldaps://vt1dceuc1001.vt1.vitesco.com", "ldaps://vt1dceuc1002.vt1.vitesco.com"]'
LDAP_SERVER_PORT: "636"
LDAP_BASE_DN: "dc=vt1,dc=vitesco,dc=com"
LDAP_USER_AUTH_ATTRIBUTE: "userPrincipalName"
