VPC_ID: vpc-12345 # vpc_id
SUBNET1_ID: subnet-12345 # the subnets of the vpc
SUBNET2_ID: subnet-54321 # the subnets of the vpc
SECRETS_MANAGER_KEY_USERNAME: "username"
SECRETS_MANAGER_KEY_PASSWORD: "password"
SECRETS_MANAGER_KEY_DN: ""
SECRETS_MANAGER_REGION: "eu-central-1"
EXCLUDE_CHARACTERS_USER: "$/`'\"\\"
EXCLUDE_CHARACTERS_PW: "/'\"\\"
EXCLUDE_CHARACTERS_NEW_PW: "@$/`'\"\\()"
LDAP_SERVER_LIST: '["ldaps://ex1dcsrv1001.ex1.example.com", "ldaps://ex1dcsrv1002.ex1.example.com"]'
LDAP_SERVER_PORT: "636"
LDAP_BASE_DN: "dc=ex1,dc=example,dc=com"
LDAP_USER_AUTH_ATTRIBUTE: "userPrincipalName"
